seml:
  executable: dataset/experiment.py #TODO: change this
  name: dataset_experiment
  output_dir: dataset/logs
  project_root_dir: ..

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:20     # max time, D-HH:MM
    partition: mllab
    qos: labcourse


fixed:
  layerwise: True

grid:
  batch_size: 
    type: choice
    options:
      - 16

pretrained:
  fixed: 
    model_file: dataset.models.pretrained
    number_forward_passes: 200

  grid: 
    model_index:
      type: range 
      min: 0
      max: 40
      step: 1
  

dense:

  fixed: 
    model_file: dataset.models.dense
    number_forward_passes: 1000

  grid: 
    model_index:
      type: range 
      min: 2
      max: 15
      step: 1




