seml:
  executable: dataset/experiment.py #TODO: change this
  name: dataset_experiment
  output_dir: dataset/logs
  project_root_dir: ..

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-02:00     # max time, D-HH:MM
    partition: mllab
    exclusive: "" #Not sure if this is going to work
    qos: labcourse

fixed:
  layerwise: True
  on_GPU: True

grid:
  batch_size: 
    type: choice
    options:
      - 16
      - 32
      - 64

pretrained:
  fixed: 
    model_file: dataset.models.pretrained
    number_forward_passes: 1

  grid: 
    params:
      model_index:
        type: range 
        min: 0
        max: 23
        step: 1

      input_size:
        type: choice
        options:
          - 300
          - 400
          - 500