dataset_class: LayerWiseDatasetv2 # TODO: Needs to be set manually to the key for the dataset.

LayerWiseDataset: # Here key for the dataset is LayerWiseDataset.
  module: src.dataset.data.dataset
  class: LayerWiseDataset # The explicit name of the dataset class.
  params:
    file_path: /home/denizkorkmaz/PycharmProjects/TUM/SS22/green-ml-daml/src/dataset/datasetGPU.csv # TODO: Needs to be set manually
    subset: pretrained
    target_layer: conv
    validation_split: 0.2
    test_split: 0.2

LayerWiseDatasetv2:
  module: src.dataset.data.dataset
  class: LayerWiseDatasetv2
  params:
    file_path: /home/denizkorkmaz/PycharmProjects/TUM/SS22/green-ml-daml/src/dataset/datasetGPU.csv
    subset: pretrained
    target_layer: conv
    validation_split: 0.2
    test_split: 0.2

model_class: GRN # TODO: Needs to be set manually to the key for the model.

polynomial_regression: # Here key for the model is polynomial_regression.
  module: src.models.polynomial_regression
  class: PolynomialRegression # The explicit name of the model class.
  params:
    degree: 3

ResidualMLP:
  module: src.models.nn_layerwise
  class: ResidualMLP
  params:
    batch_size: 64
    num_epochs: 5000
    loss: mse
    lr: 0.0001
    n_features: 5 # TODO: Needs to be set manually!
    num_epochs_overfit: 3000

GRN:
  module: src.models.nn_layerwise
  class: GRN
  params:
    batch_size: 64
    num_epochs: 500
    loss: mse
    lr: 0.0001
    n_features: 5
    num_epochs_overfit: 3000

evaluation:
  module: src.models.metrics
  metrics:
    - mae
    - mse
    - rmse
    - rmspe
    - r2