dataset_class: LayerWiseDatasetv2 # TODO: Needs to be set manually to the key for the dataset.

LayerWiseDataset: # Here key for the dataset is LayerWiseDataset.
  module: src.dataset.data.dataset
  class: LayerWiseDataset # The explicit name of the dataset class.
  params:
    file_path: /home/denizkorkmaz/PycharmProjects/TUM/SS22/green-ml-daml/src/dataset/datasetGPU.csv # TODO: Needs to be set manually
    subset: pretrained
    target_layer: conv
    validation_split: 0.2
    test_split: 0.2

LayerWiseDatasetv2:
  module: src.dataset.data.dataset
  class: LayerWiseDatasetv2
  params:
    file_path: /home/denizkorkmaz/PycharmProjects/TUM/SS22/green-ml-daml/src/dataset/datasetGPU.csv
    subset: pretrained
    target_layer: conv
    validation_split: 0.2
    test_split: 0.2

ModelWiseDataset:
  module: src.dataset.data.dataset
  class: ModelWiseDataset
  params:
    file_path: /Users/baris/Documents/green-ml-daml/src/dataset/datasetPretrainedbatch.csv # Needs to be set manually
    subset: all
    one_hot: True
    include_features: False
    augmented: True
    include_batch_size: True
    validation_split: 0.2
    test_split: 0.2


model_class: GRN # TODO: Needs to be set manually to the key for the model.

polynomial_regression: # Here key for the model is polynomial_regression.
  module: src.models.polynomial_regression
  class: PolynomialRegression # The explicit name of the model class.
  params:
    degree: 3

ResidualMLP:
  module: src.models.nn_layerwise
  class: ResidualMLP
  params:
    batch_size: 64
    num_epochs: 5000
    loss: mse
    lr: 0.0001
    n_features: 5 # TODO: Needs to be set manually!
    num_epochs_overfit: 3000

GRN:
  module: src.models.nn_layerwise
  class: GRN
  params:
    batch_size: 64
    num_epochs: 500
    loss: mse
    lr: 0.0001
    n_features: 5
    num_epochs_overfit: 3000

SimpleRNN:
  module: src.models.modelwise_nets
  class: SimpleRNN
  params:
    ragged: False
    mask: True
    batch_size: 200
    num_epochs: 500
    units: 32
    hidden_dense: 64
    loss: mse
    lr: 0.0001
    num_epochs_overfit: 3000

EmbeddedRNN:
  module: src.models.modelwise_nets
  class: EmbeddedRNN
  params:
    seq_len: 605
    feat_size: 8
    num_ops: 19
    out_dim: 10

    batch_size: 200
    num_epochs: 500
    units: 32
    hidden_dense: 16
    loss: mse
    lr: 0.0001
    num_epochs_overfit: 3000

MLP:
  module: src.models.modelwise_nets
  class: MLP
  params:
    batch_size: 200
    num_epochs: 500
    loss: mse
    lr: 0.0001
    num_epochs_overfit: 3000

Transformer:
  module: src.models.modelwise_nets
  class: Transformer
  params:
    input_shape: [605, 26]
    head_size: 64
    num_heads: 4
    ff_dim: 4
    num_transformer_blocks: 4
    mlp_units: [128]
    mlp_dropout: 0.4
    dropout: 0.5
    batch_size: 50
    num_epochs: 100
    loss: mse
    lr: 0.0001
    num_epochs_overfit: 3000

evaluation:
  module: src.models.metrics
  metrics:
    - mae
    - mse
    - rmse
    - rmspe
    - r2

